-- Calm Vault no-touch platform: initial schema.
--
-- Tables:
--   customers     — signups (one row per signup; owns one+ orgs)
--   orgs          — registered Autonomous AI Orgs (Pedersen-committed mandate)
--   attestations  — peer attestations against an org's chain
--   signing_keys  — server-side Ed25519 signing key (lazy-generated on first use)
--
-- Everything is keyed by ULID-shaped string ids generated by the Worker.

CREATE TABLE customers (
  id                          TEXT    PRIMARY KEY,
  email                       TEXT    NOT NULL UNIQUE,
  org_name                    TEXT    NOT NULL,
  primary_mandate_commitment  TEXT    NOT NULL,    -- client-supplied commitment string (free-form)
  api_key_hash                TEXT    NOT NULL UNIQUE,  -- sha-256 hex of the raw api key
  tier                        TEXT    NOT NULL DEFAULT 'free',
  stripe_customer_id          TEXT,
  created_at                  INTEGER NOT NULL    -- unix seconds
);

CREATE INDEX idx_customers_api_key_hash ON customers(api_key_hash);

CREATE TABLE orgs (
  id                  TEXT    PRIMARY KEY,
  customer_id         TEXT    NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  org_legal_name      TEXT    NOT NULL,
  founder_name        TEXT    NOT NULL,
  jurisdiction        TEXT    NOT NULL,
  -- Pedersen commitment (RFC 3526 Group 14, see calm_pact/protocol.py).
  -- commitment_c is public; commitment_r is the blinding factor (kept private but stored
  -- so the registrar can later reveal the opening if/when the customer authorizes it).
  commitment_c        TEXT    NOT NULL,
  commitment_r        TEXT    NOT NULL,
  -- Hash of the canonical genesis block (see lib/chain.ts).
  genesis_block_hash  TEXT    NOT NULL UNIQUE,
  -- Tip of this org's chain (advances as attestations are appended).
  head_block_hash     TEXT    NOT NULL,
  created_at          INTEGER NOT NULL
);

CREATE INDEX idx_orgs_customer ON orgs(customer_id);

CREATE TABLE attestations (
  id                  TEXT    PRIMARY KEY,
  attester_org_id     TEXT    NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  target_org_id       TEXT    NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  attestation_kind    TEXT    NOT NULL,
  signature           TEXT    NOT NULL,
  prev_hash           TEXT    NOT NULL,    -- head_block_hash of the target at the time of attestation
  block_hash          TEXT    NOT NULL UNIQUE,
  created_at          INTEGER NOT NULL
);

CREATE INDEX idx_attestations_target  ON attestations(target_org_id);
CREATE INDEX idx_attestations_attester ON attestations(attester_org_id);

-- Server-side signing key. Lazy-generated on first /verify or /register-org call.
-- A single-row "singleton" table; id is always 'primary'.
CREATE TABLE signing_keys (
  id              TEXT    PRIMARY KEY,
  algorithm       TEXT    NOT NULL,    -- 'Ed25519'
  private_key_b64 TEXT    NOT NULL,    -- PKCS#8 base64
  public_key_b64  TEXT    NOT NULL,    -- SPKI / raw base64
  created_at      INTEGER NOT NULL
);
